#Hombre
genero=input("Digite M si es Hombre O digite F si es Mujer: ")
if  genero=="M":
    AlturaH=int(input("Su género es másculino digite su estatura en cm: "))
    PesoH=float(input("Digite su peso actual en Kg: "))
    EdadH=int(input("Digite su edad en años: "))
    ibwH=(56.2+1.41*(AlturaH/2.54-60))
    print("Digite solo 1 opción")
    deporte=float(input("Digite su MET: caminar=2, tenis=5, bicicleta=14, correr=6, nadar=9.8: "))
    tiempo=float(input("Digite en cuanto tiempo realiza el deporte seleccionado en minutos: "))
    calorias=(tiempo*deporte*PesoH/200)
    imcH=(PesoH/(AlturaH*AlturaH))
    GrasaH=(1.20*imcH+0.23*EdadH-16.2)
    indicemeta=((13.397*PesoH)+(4.799*EdadH)-(5.677*AlturaH)+88.362)
    print("Tu peso ideal deberia de ser de: ", ibwH,"y actualmente tu peso es de: ",PesoH)
    print("Actualmente estas quemando: ", calorias, "calorías")
    print("Actualmente posees: ", GrasaH, "de grasa corporal")
    print("Tu índice metabólico basal es de: ",indicemeta)
    exit("Gracias por tu tiempo")

#Mujer
else: 
 if genero=="F":
   AlturaM=int(input("Su género es femenino digite su estatura en cm: "))
   PesoM=float(input("Digite su peso actual en Kg: "))
   edadM=int(input("Digite su edad en años: "))
   ibwM=(53.1+1.36*(AlturaM/2.54-60))
   print("Digite solo 1 opción")
   deporte=float(input("Digite su MET: caminar=2, tenis=5, bicicleta=14, correr=6, nadar=9.8: "))
   tiempo=float(input("Digite en cuanto tiempo realiza el deporte seleccionado en minutos: "))
   caloriasM=(tiempo*deporte*PesoM/200)
   imcM=(PesoM/(AlturaM*AlturaM))
   GrasaM=(1.20*imcM+0.23*edadM-5.4)
   indicemetaM=((9.24*PesoM)+(3.098*edadM)-(4.330*AlturaM)+447.593)
   print("Tu peso ideal deberia de ser de: ", ibwM,"y actualmente tu peso es de: ",PesoM)
   print("Actualmente estas quemando: ", caloriasM, "calorías")
   print("Actualmente posees:", GrasaM, "de grasa corporal")
   print("Tu índice metabólico basal es de: ",indicemetaM)
   exit("Gracias por tu tiempo")